# Generated by Django 3.1.6 on 2021-02-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ***REMOVED***

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uri',
            field=models.CharField(max_length=100, unique=True),
        ),
    ***REMOVED***
