# Generated by Django 3.1.6 on 2021-02-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ***REMOVED***

    operations = [
        migrations.RemoveField(
            model_name='render',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Render',
        ),
    ***REMOVED***
