# [START django_app]
runtime: python37

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

env_variables:
  SPOTIPY_CLIENT_ID: ""
  SPOTIPY_CLIENT_SECRET: ""
  SPOTIPY_REDIRECT_URI: ""
  GCS_BUCKET_NAME: ""
  GOOGLE_APPLICATION_CREDENTIALS: ""
  GCS_MEDIA_URL:
    ""
    # [END django_app]
